CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE DATABASE "myblog";

CREATE TABLE "users"(
    USER_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    USER_NAME VARCHAR(50) NOT NUll,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    AVATAR TEXT,
    ROLE BOOLEAN DEFAULT FALSE
);

-----------------------

CREATE TABLE "posts"(
    POST_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    AUTHOR uuid NOT NULL REFERENCES "user"(USER_ID),
    TITLE TEXT NOT NULL,
    TITLE_SLUG TEXT NOT NULL,
    CATEGORY uuid NOT NULL REFERENCES "categories"(CATE_ID),
    CONTENT TEXT NOT NULL,
    POST_IMAGE TEXT NOT NULL,
    LIKE_COUNT INTEGER DEFAULT 0,
    COMMENT_COUNT INTEGER DEFAULT 0,
    POST_ON TIMESTAMP WITH TIME ZONE NOT NULL,
    POST_UPDATE_ON TIMESTAMP WITH TIME ZONE NULL
);
------------------------

CREATE TABLE "categories"(
    CATE_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    CATEGORY TEXT NOT NULL,
    CATEGORY_SLUG TEXT NOT NULL
);
------------------------

CREATE TABLE "likes"(
    LIKE_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    LIKE_POST uuid NOT NULL REFERENCES "post"(POST_ID),
    LIKE_USER uuid NOT NULL REFERENCES "user"(USER_ID),
    LIKE_ON TIMESTAMP WITH TIME ZONE NOT NULL
);

-----------------------------

CREATE TABLE "comments"(
    COMMENT_ID uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    COMMENT_POST uuid  REFERENCES "post"(POST_ID),
    COMMENT_USER uuid NOT NULL REFERENCES "user"(USER_ID),
    COMMENT TEXT NOT NULL,
    COMMENT_ON TIMESTAMP WITH TIME ZONE NOT NULL,
    COMMENT_UPDATE_ON TIMESTAMP WITH TIME ZONE NULL
);